export const UI_EMOJI = {
  hotDeal: '🔥',
  featured: '⭐',
  ratingStar: '★',
  flashDeal: '⚡',
  feature: '✓',
  descriptionCheck: '✔',
  descriptionMarker: '📌',
  statusSuccess: '✅',
  statusError: '❌',
  statusPending: '⏳',
  statusWarning: '⚠️',
  bullet: '•',
  arrowRight: '→',
  preview: '👁️',
  run: '▶️',
  tip: '💡',
  mobileDevice: '📱',
  laptop: '💻',
  gift: '🎁',
  guide: '📖',
  folder: '📁',
  download: '📥',
  search: '🔍',
  panda: '🐼',
  bamboo: '🎋',
} as const;

export const DESCRIPTION_EMOJI = new Set([
  UI_EMOJI.descriptionCheck,
  UI_EMOJI.feature,
  UI_EMOJI.statusSuccess,
  UI_EMOJI.statusError,
  UI_EMOJI.statusWarning,
  UI_EMOJI.hotDeal,
  UI_EMOJI.tip,
  UI_EMOJI.mobileDevice,
  UI_EMOJI.laptop,
  UI_EMOJI.gift,
  UI_EMOJI.descriptionMarker,
]);
