#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { getActiveLangCodes, getLanguageNames } = require('../config/languageInventory');

// Get languages dynamically from config (not hardcoded)
const getLanguagesMap = () => {
  const activeLangs = getActiveLangCodes();
  const langNames = getLanguageNames();
  const map = {};
  activeLangs.forEach(lang => {
    map[lang] = { name: langNames[lang], flag: lang.toUpperCase() };
  });
  return map;
};

const LANGUAGES = getLanguagesMap();

// Files to translate with priority (higher number = higher priority)
const FILES_TO_TRANSLATE = {
  'admin-translation-override': 10,
  'admin-translation-batch': 9,
  'customers': 8,
  'notifications': 8,
  'admin-banners': 7,
  'order-confirmation': 7,
  'order-success': 7,
  'pages': 7,
  'profile': 6,
  'shopping-guide': 6,
  'pagination': 6,
  'frontend-import': 5,
  'import': 5,
  'login': 5,
  'newsletter': 5,
  'breadcrumbs': 4
};

// Translation strings with professional context
const TRANSLATION_MAP = {
  pt: {
    "admin_override_title": "Substituição Manual de Tradução",
    "admin_override_subtitle": "Substitua manualmente uma tradução específica com log de auditoria completo",
    "admin_override_entity_id": "ID da Entidade",
    "admin_override_entity_id_placeholder": "ex: prod_12345",
    "admin_override_entity_id_help": "ID do Produto, Avaliação ou outra entidade",
    "admin_override_entity_type": "Tipo de Entidade",
    "admin_override_entity_type_product": "Produto",
    "admin_override_entity_type_review": "Avaliação",
    "admin_override_entity_type_category": "Categoria",
    "admin_override_entity_type_feature": "Recurso",
    "admin_override_entity_type_spec": "Especificação",
    "admin_override_entity_type_description": "Descrição",
    "admin_override_entity_type_ad_hoc": "Texto Ad-hoc",
    "admin_override_language": "Idioma",
    "admin_override_lang_vi": "Vietnamita",
    "admin_override_lang_en": "Inglês",
    "admin_override_lang_pt": "Português",
    "admin_override_lang_fr": "Francês",
    "admin_override_lang_de": "Alemão",
    "admin_override_lang_it": "Italiano",
    "admin_override_lang_es": "Espanhol",
    "admin_override_lang_nl": "Holandês",
    "admin_override_lang_sv": "Sueco",
    "admin_override_old_value": "Valor Atual",
    "admin_override_old_value_placeholder": "Tradução atual (opcional - para referência)",
    "admin_override_old_value_help": "Deixe vazio se desconhecido",
    "admin_override_new_value": "Novo Valor",
    "admin_override_new_value_placeholder": "Digite a tradução corrigida",
    "admin_override_new_value_help": "Isto substituirá o valor atual",
    "admin_override_reason": "Motivo da Substituição",
    "admin_override_reason_placeholder": "Explique por que esta substituição é necessária",
    "admin_override_reason_help": "Isto será registrado no trilha de auditoria",
    "admin_override_hide_preview": "Ocultar Visualização",
    "admin_override_show_preview": "Mostrar Visualização",
    "admin_override_saving": "Salvando...",
    "admin_override_save": "Salvar Substituição",
    "admin_override_preview_title": "Visualização",
    "admin_override_recent_title": "Substituições Recentes",
    "admin_override_use_this": "Use Este",
    "admin_batch_override_title": "Substituição em Lote de Tradução",
    "admin_batch_override_subtitle": "Carregue CSV para substituir várias traduções de uma vez",
    "admin_batch_upload_title": "Carregar Arquivo CSV",
    "admin_batch_upload_drag": "Arraste e solte o arquivo CSV aqui ou clique para procurar",
    "admin_batch_upload_format": "Formato: ID da Entidade, Tipo de Entidade, Idioma de Destino, Valor Antigo, Novo Valor, Motivo",
    "admin_batch_download_template": "Baixar Modelo",
    "admin_batch_add_manual": "Adicionar Linha Manual",
    "admin_batch_preview_title": "Visualizar Dados",
    "admin_batch_hide_preview": "Ocultar",
    "admin_batch_show_preview": "Mostrar",
    "admin_batch_col_entity": "ID da Entidade",
    "admin_batch_col_type": "Tipo",
    "admin_batch_col_lang": "Idioma",
    "admin_batch_col_old": "Valor Antigo",
    "admin_batch_col_new": "Novo Valor",
    "admin_batch_col_new_value": "Novo Valor",
    "admin_batch_col_reason": "Motivo",
    "admin_batch_col_status": "Status",
    "admin_batch_col_actions": "Ações",
    "admin_batch_example_old": "Texto Antigo",
    "admin_batch_example_new": "Novo Texto",
    "admin_batch_example_reason": "Correção de gramática",
    "admin_batch_results_title": "Resultados do Lote",
    "admin_batch_result_total": "Total Processado",
    "admin_batch_result_success": "Sucesso",
    "admin_batch_result_failure": "Falha",
    "admin_batch_failures_title": "Linhas com Falha",
    "admin_batch_export_results": "Exportar Resultados",
    "admin_batch_processing": "Processando...",
    "admin_batch_process": "Processar Lote"
  },
  fr: {
    "admin_override_title": "Remplacement de Traduction Manuel",
    "admin_override_subtitle": "Remplacez manuellement une traduction spécifique avec journalisation complète",
    "admin_override_entity_id": "ID d'Entité",
    "admin_override_entity_id_placeholder": "ex: prod_12345",
    "admin_override_entity_id_help": "ID de Produit, Avis ou autre entité",
    "admin_override_entity_type": "Type d'Entité",
    "admin_override_entity_type_product": "Produit",
    "admin_override_entity_type_review": "Avis",
    "admin_override_entity_type_category": "Catégorie",
    "admin_override_entity_type_feature": "Fonctionnalité",
    "admin_override_entity_type_spec": "Spécification",
    "admin_override_entity_type_description": "Description",
    "admin_override_entity_type_ad_hoc": "Texte Ad-hoc",
    "admin_override_language": "Langue",
    "admin_override_lang_vi": "Vietnamien",
    "admin_override_lang_en": "Anglais",
    "admin_override_lang_pt": "Portugais",
    "admin_override_lang_fr": "Français",
    "admin_override_lang_de": "Allemand",
    "admin_override_lang_it": "Italien",
    "admin_override_lang_es": "Espagnol",
    "admin_override_lang_nl": "Néerlandais",
    "admin_override_lang_sv": "Suédois",
    "admin_override_old_value": "Valeur Actuelle",
    "admin_override_old_value_placeholder": "Traduction actuelle (optionnel - pour référence)",
    "admin_override_old_value_help": "Laissez vide si inconnu",
    "admin_override_new_value": "Nouvelle Valeur",
    "admin_override_new_value_placeholder": "Entrez la traduction corrigée",
    "admin_override_new_value_help": "Cela remplacera la valeur actuelle",
    "admin_override_reason": "Raison du Remplacement",
    "admin_override_reason_placeholder": "Expliquez pourquoi ce remplacement est nécessaire",
    "admin_override_reason_help": "Cela sera enregistré dans le journal d'audit",
    "admin_override_hide_preview": "Masquer l'Aperçu",
    "admin_override_show_preview": "Afficher l'Aperçu",
    "admin_override_saving": "Enregistrement...",
    "admin_override_save": "Enregistrer le Remplacement",
    "admin_override_preview_title": "Aperçu",
    "admin_override_recent_title": "Remplacements Récents",
    "admin_override_use_this": "Utiliser Celui-ci",
    "admin_batch_override_title": "Remplacement de Traduction en Lot",
    "admin_batch_override_subtitle": "Téléchargez un CSV pour remplacer plusieurs traductions à la fois",
    "admin_batch_upload_title": "Télécharger un Fichier CSV",
    "admin_batch_upload_drag": "Glissez-déposez le fichier CSV ici ou cliquez pour parcourir",
    "admin_batch_upload_format": "Format: ID d'Entité, Type d'Entité, Langue Cible, Ancienne Valeur, Nouvelle Valeur, Raison",
    "admin_batch_download_template": "Télécharger le Modèle",
    "admin_batch_add_manual": "Ajouter une Ligne Manuelle",
    "admin_batch_preview_title": "Prévisualiser les Données",
    "admin_batch_hide_preview": "Masquer",
    "admin_batch_show_preview": "Afficher",
    "admin_batch_col_entity": "ID d'Entité",
    "admin_batch_col_type": "Type",
    "admin_batch_col_lang": "Langue",
    "admin_batch_col_old": "Ancienne Valeur",
    "admin_batch_col_new": "Nouvelle Valeur",
    "admin_batch_col_new_value": "Nouvelle Valeur",
    "admin_batch_col_reason": "Raison",
    "admin_batch_col_status": "Statut",
    "admin_batch_col_actions": "Actions",
    "admin_batch_example_old": "Ancien Texte",
    "admin_batch_example_new": "Nouveau Texte",
    "admin_batch_example_reason": "Correction grammaticale",
    "admin_batch_results_title": "Résultats du Lot",
    "admin_batch_result_total": "Total Traité",
    "admin_batch_result_success": "Succès",
    "admin_batch_result_failure": "Échec",
    "admin_batch_failures_title": "Lignes Échouées",
    "admin_batch_export_results": "Exporter les Résultats",
    "admin_batch_processing": "Traitement en cours...",
    "admin_batch_process": "Traiter le Lot"
  },
  de: {
    "admin_override_title": "Manuelle Übersetzungsüberschreibung",
    "admin_override_subtitle": "Überschreiben Sie manuell eine bestimmte Übersetzung mit vollständiger Audit-Protokollierung",
    "admin_override_entity_id": "Entitäts-ID",
    "admin_override_entity_id_placeholder": "z.B. prod_12345",
    "admin_override_entity_id_help": "Produkt-, Bewertungs- oder andere Entitäts-ID",
    "admin_override_entity_type": "Entitätstyp",
    "admin_override_entity_type_product": "Produkt",
    "admin_override_entity_type_review": "Bewertung",
    "admin_override_entity_type_category": "Kategorie",
    "admin_override_entity_type_feature": "Funktion",
    "admin_override_entity_type_spec": "Spezifikation",
    "admin_override_entity_type_description": "Beschreibung",
    "admin_override_entity_type_ad_hoc": "Ad-hoc-Text",
    "admin_override_language": "Sprache",
    "admin_override_lang_vi": "Vietnamesisch",
    "admin_override_lang_en": "Englisch",
    "admin_override_lang_pt": "Portugiesisch",
    "admin_override_lang_fr": "Französisch",
    "admin_override_lang_de": "Deutsch",
    "admin_override_lang_it": "Italienisch",
    "admin_override_lang_es": "Spanisch",
    "admin_override_lang_nl": "Niederländisch",
    "admin_override_lang_sv": "Schwedisch",
    "admin_override_old_value": "Aktueller Wert",
    "admin_override_old_value_placeholder": "Aktuelle Übersetzung (optional - als Referenz)",
    "admin_override_old_value_help": "Leer lassen, falls unbekannt",
    "admin_override_new_value": "Neuer Wert",
    "admin_override_new_value_placeholder": "Geben Sie die korrigierte Übersetzung ein",
    "admin_override_new_value_help": "Dies ersetzt den aktuellen Wert",
    "admin_override_reason": "Grund für Überschreibung",
    "admin_override_reason_placeholder": "Erklären Sie, warum diese Überschreibung erforderlich ist",
    "admin_override_reason_help": "Dies wird im Audit-Protokoll protokolliert",
    "admin_override_hide_preview": "Vorschau ausblenden",
    "admin_override_show_preview": "Vorschau anzeigen",
    "admin_override_saving": "Wird gespeichert...",
    "admin_override_save": "Überschreibung speichern",
    "admin_override_preview_title": "Vorschau",
    "admin_override_recent_title": "Letzte Überschreibungen",
    "admin_override_use_this": "Diesen verwenden",
    "admin_batch_override_title": "Batch-Übersetzungsüberschreibung",
    "admin_batch_override_subtitle": "Laden Sie CSV hoch, um mehrere Übersetzungen auf einmal zu überschreiben",
    "admin_batch_upload_title": "CSV-Datei hochladen",
    "admin_batch_upload_drag": "CSV-Datei hier ablegen oder zum Durchsuchen anklicken",
    "admin_batch_upload_format": "Format: Entitäts-ID, Entitätstyp, Zielsprache, Alter Wert, Neuer Wert, Grund",
    "admin_batch_download_template": "Vorlage herunterladen",
    "admin_batch_add_manual": "Manuelle Zeile hinzufügen",
    "admin_batch_preview_title": "Vorschau der Daten",
    "admin_batch_hide_preview": "Ausblenden",
    "admin_batch_show_preview": "Anzeigen",
    "admin_batch_col_entity": "Entitäts-ID",
    "admin_batch_col_type": "Typ",
    "admin_batch_col_lang": "Sprache",
    "admin_batch_col_old": "Alter Wert",
    "admin_batch_col_new": "Neuer Wert",
    "admin_batch_col_new_value": "Neuer Wert",
    "admin_batch_col_reason": "Grund",
    "admin_batch_col_status": "Status",
    "admin_batch_col_actions": "Aktionen",
    "admin_batch_example_old": "Alter Text",
    "admin_batch_example_new": "Neuer Text",
    "admin_batch_example_reason": "Grammatik korrigiert",
    "admin_batch_results_title": "Batch-Ergebnisse",
    "admin_batch_result_total": "Gesamt verarbeitet",
    "admin_batch_result_success": "Erfolg",
    "admin_batch_result_failure": "Fehler",
    "admin_batch_failures_title": "Fehlgeschlagene Zeilen",
    "admin_batch_export_results": "Ergebnisse exportieren",
    "admin_batch_processing": "Wird verarbeitet...",
    "admin_batch_process": "Batch verarbeiten"
  },
  it: {
    "admin_override_title": "Sostituzione Traduzione Manuale",
    "admin_override_subtitle": "Sostituisci manualmente una traduzione specifica con registrazione di audit completa",
    "admin_override_entity_id": "ID Entità",
    "admin_override_entity_id_placeholder": "es: prod_12345",
    "admin_override_entity_id_help": "ID Prodotto, Recensione o altra entità",
    "admin_override_entity_type": "Tipo di Entità",
    "admin_override_entity_type_product": "Prodotto",
    "admin_override_entity_type_review": "Recensione",
    "admin_override_entity_type_category": "Categoria",
    "admin_override_entity_type_feature": "Funzionalità",
    "admin_override_entity_type_spec": "Specifica",
    "admin_override_entity_type_description": "Descrizione",
    "admin_override_entity_type_ad_hoc": "Testo Ad-hoc",
    "admin_override_language": "Lingua",
    "admin_override_lang_vi": "Vietnamita",
    "admin_override_lang_en": "Inglese",
    "admin_override_lang_pt": "Portoghese",
    "admin_override_lang_fr": "Francese",
    "admin_override_lang_de": "Tedesco",
    "admin_override_lang_it": "Italiano",
    "admin_override_lang_es": "Spagnolo",
    "admin_override_lang_nl": "Olandese",
    "admin_override_lang_sv": "Svedese",
    "admin_override_old_value": "Valore Attuale",
    "admin_override_old_value_placeholder": "Traduzione attuale (opzionale - per riferimento)",
    "admin_override_old_value_help": "Lascia vuoto se sconosciuto",
    "admin_override_new_value": "Nuovo Valore",
    "admin_override_new_value_placeholder": "Inserisci la traduzione corretta",
    "admin_override_new_value_help": "Questo sostituirà il valore attuale",
    "admin_override_reason": "Motivo della Sostituzione",
    "admin_override_reason_placeholder": "Spiega perché questa sostituzione è necessaria",
    "admin_override_reason_help": "Questo verrà registrato nel registro di audit",
    "admin_override_hide_preview": "Nascondi Anteprima",
    "admin_override_show_preview": "Mostra Anteprima",
    "admin_override_saving": "Salvataggio in corso...",
    "admin_override_save": "Salva Sostituzione",
    "admin_override_preview_title": "Anteprima",
    "admin_override_recent_title": "Sostituzioni Recenti",
    "admin_override_use_this": "Usa Questo",
    "admin_batch_override_title": "Sostituzione Traduzione in Lotto",
    "admin_batch_override_subtitle": "Carica CSV per sostituire più traduzioni contemporaneamente",
    "admin_batch_upload_title": "Carica File CSV",
    "admin_batch_upload_drag": "Trascina e rilascia il file CSV qui o fai clic per sfogliare",
    "admin_batch_upload_format": "Formato: ID Entità, Tipo Entità, Lingua Destinazione, Valore Vecchio, Nuovo Valore, Motivo",
    "admin_batch_download_template": "Scarica Modello",
    "admin_batch_add_manual": "Aggiungi Riga Manuale",
    "admin_batch_preview_title": "Anteprima Dati",
    "admin_batch_hide_preview": "Nascondi",
    "admin_batch_show_preview": "Mostra",
    "admin_batch_col_entity": "ID Entità",
    "admin_batch_col_type": "Tipo",
    "admin_batch_col_lang": "Lingua",
    "admin_batch_col_old": "Valore Vecchio",
    "admin_batch_col_new": "Nuovo Valore",
    "admin_batch_col_new_value": "Nuovo Valore",
    "admin_batch_col_reason": "Motivo",
    "admin_batch_col_status": "Stato",
    "admin_batch_col_actions": "Azioni",
    "admin_batch_example_old": "Testo Vecchio",
    "admin_batch_example_new": "Nuovo Testo",
    "admin_batch_example_reason": "Correzione grammaticale",
    "admin_batch_results_title": "Risultati Lotto",
    "admin_batch_result_total": "Totale Elaborato",
    "admin_batch_result_success": "Successo",
    "admin_batch_result_failure": "Errore",
    "admin_batch_failures_title": "Righe Non Riuscite",
    "admin_batch_export_results": "Esporta Risultati",
    "admin_batch_processing": "Elaborazione in corso...",
    "admin_batch_process": "Elabora Lotto"
  },
  es: {
    "admin_override_title": "Anulación de Traducción Manual",
    "admin_override_subtitle": "Anule manualmente una traducción específica con registro de auditoría completo",
    "admin_override_entity_id": "ID de Entidad",
    "admin_override_entity_id_placeholder": "p.ej., prod_12345",
    "admin_override_entity_id_help": "ID de Producto, Reseña u otra entidad",
    "admin_override_entity_type": "Tipo de Entidad",
    "admin_override_entity_type_product": "Producto",
    "admin_override_entity_type_review": "Reseña",
    "admin_override_entity_type_category": "Categoría",
    "admin_override_entity_type_feature": "Función",
    "admin_override_entity_type_spec": "Especificación",
    "admin_override_entity_type_description": "Descripción",
    "admin_override_entity_type_ad_hoc": "Texto Ad-hoc",
    "admin_override_language": "Idioma",
    "admin_override_lang_vi": "Vietnamita",
    "admin_override_lang_en": "Inglés",
    "admin_override_lang_pt": "Portugués",
    "admin_override_lang_fr": "Francés",
    "admin_override_lang_de": "Alemán",
    "admin_override_lang_it": "Italiano",
    "admin_override_lang_es": "Español",
    "admin_override_lang_nl": "Neerlandés",
    "admin_override_lang_sv": "Sueco",
    "admin_override_old_value": "Valor Actual",
    "admin_override_old_value_placeholder": "Traducción actual (opcional - para referencia)",
    "admin_override_old_value_help": "Deje vacío si no lo sabe",
    "admin_override_new_value": "Nuevo Valor",
    "admin_override_new_value_placeholder": "Ingrese la traducción corregida",
    "admin_override_new_value_help": "Esto reemplazará el valor actual",
    "admin_override_reason": "Razón de la Anulación",
    "admin_override_reason_placeholder": "Explique por qué es necesaria esta anulación",
    "admin_override_reason_help": "Esto se registrará en el registro de auditoría",
    "admin_override_hide_preview": "Ocultar Vista Previa",
    "admin_override_show_preview": "Mostrar Vista Previa",
    "admin_override_saving": "Guardando...",
    "admin_override_save": "Guardar Anulación",
    "admin_override_preview_title": "Vista Previa",
    "admin_override_recent_title": "Anulaciones Recientes",
    "admin_override_use_this": "Usar Este",
    "admin_batch_override_title": "Anulación de Traducción por Lotes",
    "admin_batch_override_subtitle": "Cargue CSV para anular varias traducciones a la vez",
    "admin_batch_upload_title": "Cargar Archivo CSV",
    "admin_batch_upload_drag": "Arrastra y suelta el archivo CSV aquí o haz clic para explorar",
    "admin_batch_upload_format": "Formato: ID de Entidad, Tipo de Entidad, Idioma Destino, Valor Antiguo, Nuevo Valor, Razón",
    "admin_batch_download_template": "Descargar Plantilla",
    "admin_batch_add_manual": "Agregar Fila Manual",
    "admin_batch_preview_title": "Datos de Vista Previa",
    "admin_batch_hide_preview": "Ocultar",
    "admin_batch_show_preview": "Mostrar",
    "admin_batch_col_entity": "ID de Entidad",
    "admin_batch_col_type": "Tipo",
    "admin_batch_col_lang": "Idioma",
    "admin_batch_col_old": "Valor Antiguo",
    "admin_batch_col_new": "Nuevo Valor",
    "admin_batch_col_new_value": "Nuevo Valor",
    "admin_batch_col_reason": "Razón",
    "admin_batch_col_status": "Estado",
    "admin_batch_col_actions": "Acciones",
    "admin_batch_example_old": "Texto Antiguo",
    "admin_batch_example_new": "Texto Nuevo",
    "admin_batch_example_reason": "Corrección de gramática",
    "admin_batch_results_title": "Resultados del Lote",
    "admin_batch_result_total": "Total Procesado",
    "admin_batch_result_success": "Éxito",
    "admin_batch_result_failure": "Error",
    "admin_batch_failures_title": "Filas Fallidas",
    "admin_batch_export_results": "Exportar Resultados",
    "admin_batch_processing": "Procesando...",
    "admin_batch_process": "Procesar Lote"
  },
  nl: {
    "admin_override_title": "Handmatige Vertaaloverride",
    "admin_override_subtitle": "Handmatig een specifieke vertaling onderdrukken met volledige audit logging",
    "admin_override_entity_id": "Entiteit-ID",
    "admin_override_entity_id_placeholder": "bijv. prod_12345",
    "admin_override_entity_id_help": "Product-, Review- of andere entiteit-ID",
    "admin_override_entity_type": "Entiteittype",
    "admin_override_entity_type_product": "Product",
    "admin_override_entity_type_review": "Review",
    "admin_override_entity_type_category": "Categorie",
    "admin_override_entity_type_feature": "Functie",
    "admin_override_entity_type_spec": "Specificatie",
    "admin_override_entity_type_description": "Beschrijving",
    "admin_override_entity_type_ad_hoc": "Ad-hoc-tekst",
    "admin_override_language": "Taal",
    "admin_override_lang_vi": "Vietnamees",
    "admin_override_lang_en": "Engels",
    "admin_override_lang_pt": "Portugees",
    "admin_override_lang_fr": "Frans",
    "admin_override_lang_de": "Duits",
    "admin_override_lang_it": "Italiaans",
    "admin_override_lang_es": "Spaans",
    "admin_override_lang_nl": "Nederlands",
    "admin_override_lang_sv": "Zweeds",
    "admin_override_old_value": "Huidige Waarde",
    "admin_override_old_value_placeholder": "Huidige vertaling (optioneel - ter referentie)",
    "admin_override_old_value_help": "Leeg laten als onbekend",
    "admin_override_new_value": "Nieuwe Waarde",
    "admin_override_new_value_placeholder": "Voer de gecorrigeerde vertaling in",
    "admin_override_new_value_help": "Dit zal de huidige waarde vervangen",
    "admin_override_reason": "Reden voor Override",
    "admin_override_reason_placeholder": "Leg uit waarom deze override nodig is",
    "admin_override_reason_help": "Dit zal worden geregistreerd in het auditlogboek",
    "admin_override_hide_preview": "Voorbeeld verbergen",
    "admin_override_show_preview": "Voorbeeld tonen",
    "admin_override_saving": "Opslaan...",
    "admin_override_save": "Override opslaan",
    "admin_override_preview_title": "Voorbeeld",
    "admin_override_recent_title": "Recente Overrides",
    "admin_override_use_this": "Dit gebruiken",
    "admin_batch_override_title": "Batch-vertaaloverride",
    "admin_batch_override_subtitle": "Upload CSV om meerdere vertalingen tegelijk onder druk in te stellen",
    "admin_batch_upload_title": "CSV-bestand uploaden",
    "admin_batch_upload_drag": "Sleep CSV-bestand hier of klik om te bladeren",
    "admin_batch_upload_format": "Formaat: Entiteit-ID, Entiteittype, Doeltaal, Oude waarde, Nieuwe waarde, Reden",
    "admin_batch_download_template": "Sjabloon downloaden",
    "admin_batch_add_manual": "Handmatige rij toevoegen",
    "admin_batch_preview_title": "Gegevens bekijken",
    "admin_batch_hide_preview": "Verbergen",
    "admin_batch_show_preview": "Tonen",
    "admin_batch_col_entity": "Entiteit-ID",
    "admin_batch_col_type": "Type",
    "admin_batch_col_lang": "Taal",
    "admin_batch_col_old": "Oude waarde",
    "admin_batch_col_new": "Nieuwe waarde",
    "admin_batch_col_new_value": "Nieuwe waarde",
    "admin_batch_col_reason": "Reden",
    "admin_batch_col_status": "Status",
    "admin_batch_col_actions": "Acties",
    "admin_batch_example_old": "Oude tekst",
    "admin_batch_example_new": "Nieuwe tekst",
    "admin_batch_example_reason": "Grammaticacorrectie",
    "admin_batch_results_title": "Batchresultaten",
    "admin_batch_result_total": "Totaal verwerkt",
    "admin_batch_result_success": "Succes",
    "admin_batch_result_failure": "Fout",
    "admin_batch_failures_title": "Mislukte rijen",
    "admin_batch_export_results": "Resultaten exporteren",
    "admin_batch_processing": "Verwerken...",
    "admin_batch_process": "Batch verwerken"
  },
  sv: {
    "admin_override_title": "Manuell Översättningsöverride",
    "admin_override_subtitle": "Åsidosätt manuellt en specifik översättning med fullständig revisionsgranskning",
    "admin_override_entity_id": "Entitets-ID",
    "admin_override_entity_id_placeholder": "t.ex. prod_12345",
    "admin_override_entity_id_help": "Produkt-, Recension- eller annan enhets-ID",
    "admin_override_entity_type": "Enhetstyp",
    "admin_override_entity_type_product": "Produkt",
    "admin_override_entity_type_review": "Recension",
    "admin_override_entity_type_category": "Kategori",
    "admin_override_entity_type_feature": "Funktion",
    "admin_override_entity_type_spec": "Specifikation",
    "admin_override_entity_type_description": "Beskrivning",
    "admin_override_entity_type_ad_hoc": "Ad-hoc-text",
    "admin_override_language": "Språk",
    "admin_override_lang_vi": "Vietnamesiska",
    "admin_override_lang_en": "Engelska",
    "admin_override_lang_pt": "Portugisiska",
    "admin_override_lang_fr": "Franska",
    "admin_override_lang_de": "Tyska",
    "admin_override_lang_it": "Italienska",
    "admin_override_lang_es": "Spanska",
    "admin_override_lang_nl": "Nederländska",
    "admin_override_lang_sv": "Svenska",
    "admin_override_old_value": "Aktuellt värde",
    "admin_override_old_value_placeholder": "Aktuell översättning (valfritt - som referens)",
    "admin_override_old_value_help": "Lämna tomt om det är okänt",
    "admin_override_new_value": "Nytt värde",
    "admin_override_new_value_placeholder": "Ange den korrigerade översättningen",
    "admin_override_new_value_help": "Det här kommer att ersätta det aktuella värdet",
    "admin_override_reason": "Anledning till Override",
    "admin_override_reason_placeholder": "Förklara varför denna åsidosättning är nödvändig",
    "admin_override_reason_help": "Det här kommer att loggas i granskningsloggenen",
    "admin_override_hide_preview": "Dölj förhandsgranskning",
    "admin_override_show_preview": "Visa förhandsgranskning",
    "admin_override_saving": "Sparar...",
    "admin_override_save": "Spara Override",
    "admin_override_preview_title": "Förhandsgranskning",
    "admin_override_recent_title": "Senaste Overrides",
    "admin_override_use_this": "Använd denna",
    "admin_batch_override_title": "Batch-översättningsöverride",
    "admin_batch_override_subtitle": "Ladda upp CSV för att åsidosätta flera översättningar samtidigt",
    "admin_batch_upload_title": "Ladda upp CSV-fil",
    "admin_batch_upload_drag": "Dra och släpp CSV-fil här eller klicka för att bläddra",
    "admin_batch_upload_format": "Format: Entitets-ID, Enhetstyp, Målspråk, Gammalt värde, Nytt värde, Anledning",
    "admin_batch_download_template": "Ladda ned mall",
    "admin_batch_add_manual": "Lägg till manuell rad",
    "admin_batch_preview_title": "Förhandsgranska data",
    "admin_batch_hide_preview": "Dölj",
    "admin_batch_show_preview": "Visa",
    "admin_batch_col_entity": "Entitets-ID",
    "admin_batch_col_type": "Typ",
    "admin_batch_col_lang": "Språk",
    "admin_batch_col_old": "Gammalt värde",
    "admin_batch_col_new": "Nytt värde",
    "admin_batch_col_new_value": "Nytt värde",
    "admin_batch_col_reason": "Anledning",
    "admin_batch_col_status": "Status",
    "admin_batch_col_actions": "Åtgärder",
    "admin_batch_example_old": "Gammal text",
    "admin_batch_example_new": "Ny text",
    "admin_batch_example_reason": "Grammatikkorrigering",
    "admin_batch_results_title": "Batchresultat",
    "admin_batch_result_total": "Totalt behandlat",
    "admin_batch_result_success": "Framgång",
    "admin_batch_result_failure": "Fel",
    "admin_batch_failures_title": "Misslyckade rader",
    "admin_batch_export_results": "Exportera resultat",
    "admin_batch_processing": "Bearbetar...",
    "admin_batch_process": "Bearbeta batch"
  }
};

const localesDir = path.join(__dirname, 'src', 'locales');

/**
 * Translate a JSON file by replacing all English values with translations
 */
function translateFile(filename, langCode, translations) {
  const defaultLang = getDefaultLanguage().code;
  const defaultFilePath = path.join(localesDir, defaultLang, `${filename}.json`);
  const targetFilePath = path.join(localesDir, langCode, `${filename}.json`);

  try {
    const defaultContent = JSON.parse(fs.readFileSync(defaultFilePath, 'utf-8'));
    const translatedContent = {};

    // Keep the same structure and key names, but translate values
    for (const [key, defaultValue] of Object.entries(defaultContent)) {
      if (translations && translations[key]) {
        translatedContent[key] = translations[key];
      } else {
        // Keep default language value if no translation provided
        translatedContent[key] = defaultValue;
      }
    }

    // Write the translated file
    fs.writeFileSync(targetFilePath, JSON.stringify(translatedContent, null, 2));
    return true;
  } catch (err) {
    console.error(`Error translating ${filename} to ${langCode}: ${err.message}`);
    return false;
  }
}

/**
 * Get files to translate sorted by priority
 */
function getFilesToTranslate() {
  return Object.keys(FILES_TO_TRANSLATE).sort((a, b) => {
    return FILES_TO_TRANSLATE[b] - FILES_TO_TRANSLATE[a];
  });
}

console.log('Starting translation process...\n');

const filesToTranslate = getFilesToTranslate();
console.log(`Found ${filesToTranslate.length} files to translate\n`);

let totalFiles = 0;
let successCount = 0;
let failureCount = 0;

// Translate files for each language
for (const langCode of Object.keys(LANGUAGES)) {
  console.log(`\n>>> Translating to ${LANGUAGES[langCode].name} (${langCode.toUpperCase()})`);
  console.log('='.repeat(50));

  const translations = TRANSLATION_MAP[langCode] || {};

  for (const filename of filesToTranslate) {
    const priority = FILES_TO_TRANSLATE[filename];
    const priorityStr = '[HIGH]\'.padEnd(7) + \' \' if (priority >= 8) else \'[MED] \' if (priority >= 5) else \'[LOW] ';

    if (translateFile(filename, langCode, translations)) {
      console.log(`${priorityStr} ✓ ${filename}`);
      successCount++;
    } else {
      console.log(`${priorityStr} ✗ ${filename}`);
      failureCount++;
    }
    totalFiles++;
  }
}

console.log('\n' + '='.repeat(50));
console.log(`Translation complete!`);
console.log(`Total files processed: ${totalFiles}`);
console.log(`Successful: ${successCount}`);
console.log(`Failed: ${failureCount}`);
