const CLI_SYMBOLS = {
  success: '✅',
  error: '❌',
  warning: '⚠️',
  info: 'ℹ',
  check: '✓',
  cross: '✗',
  report: '📄',
  seed: '🌱',
  test: '🧪',
  run: '▶️',
  package: '📦',
  tag: '🏷️',
  skip: '⏭️',
  list: '📋',
  globe: '🌐',
  building: '🏢',
  idea: '💡',
  progress: '🔄',
  products: '🛍️',
  target: '🎯',
  cleanup: '🧹',
  chart: '📊',
  languages: '🗣️',
  duration: '⏱️',
  wait: '⏳',
  search: '🔍',
  save: '💾',
  edit: '📝',
  location: '📍',
  celebration: '🎉',
  sparkles: '✨',
  lock: '🔒',
  unlock: '🔓',
  bullet: '•',
  divider: '═',
  importanceCritical: '🔴',
  importanceHigh: '🟠',
  importanceMedium: '🟡',
  importanceLow: '🟢',
};

module.exports = { CLI_SYMBOLS };
